### PR TITLE
Code simplifications with no modification to functionality

### LINKED ISSUE #20: Can we remove zzz.R?
It seems like it doesn't do anything anymore:

https://github.com/nlmixr2/nlmixr2plot/blob/094a0b1e74e910f9b6d97b337bd422d8b5882eb1/R/zzz.R

### PR DESCRIPTION
**Pull request by billdenney**
Fix #20

### CODE REVIEW

**Comment by mattfidler** [comment]
By default I have been trying to put the import/exports in the `nlmixr2plot` or `packgeName.R` which I think follows the convention.

**Comment by billdenney** [comment]
Maybe my understanding is incorrect.

I dropped the function imports because most of the code used the `::` notation.  I simplified the code by making (almost) all the code use `::`, and then I further simplified the code by removing the imports themselves.

Since they were not also exports, I thought that didn't change any functionality.  Am I missing something?

**Comment by mattfidler** [comment]
I think there is a scoping issue if you don't have the function imports.  

If you can get it to pass without the imports that would be fine with me.

**Comment by billdenney** [comment]
It passes with updated CI code, so I will merge.

**Pull request merged**
